/*
 * Java entity class for "PisCake" 
 * Created on 2020/02/11 - Time 16:31:10 
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package bao.nguyen.PIS.entity;

import bao.nguyen.PIS.common.BaseEntity
import javax.persistence.*
import javax.validation.constraints.*;
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UpdateTimestamp


  
/**
 * Domain class for entity "PisCake"
 *
 * @author Bao Nguyen
 *
 */
@Entity
@Table(name ="pis_cake")
data class PisCake (
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // 
     @NotNull
    @Size( min = 1, max = 255 )
    var name : String = String(),

	// 
    var price :Int ? = null,

     //
     var piece_on_tray :Int ? = null,
    
    // PisSetting
    @OneToMany(mappedBy="pisCake")
    var listOfPisSetting:List<PisSetting> = emptyList() ,
    
    // PisDeliveryDetail
    @OneToMany(mappedBy="pisCake")
    var listOfPisDeliveryDetail:List<PisDeliveryDetail> = emptyList() ,
    
    // PisDailySale
    @OneToMany(mappedBy="pisCake")
    var listOfPisDailySale:List<PisDailySale> = emptyList() ,
    
    // PisStore
    @OneToMany(mappedBy="pisCake")
    var listOfPisStore:List<PisStore> = emptyList() ,
    
    // PisRequest
    @OneToMany(mappedBy="pisCake")
    var listOfPisRequest:List<PisRequest> = emptyList() 
): BaseEntity<Int>()
