/*
 * Java entity class for "PisDeliveryDetail" 
 * Created on 2020/02/23 - Time 22:53:43 
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package bao.nguyen.PIS.entity;

import bao.nguyen.PIS.common.BaseEntity

import javax.persistence.*
import javax.validation.constraints.*;
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UpdateTimestamp

import java.util.Date;


/**
 * Domain class for entity "PisDeliveryDetail"
 *
 * @author Bao Nguyen
 *
 */
@Entity
@Table(name ="pis_delivery_detail")
data class PisDeliveryDetail (
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // 
     var createAt : Date? = null,

	// 
    var piece :Int ? = null,

	// 
    var tray : Float? = null,
    
    // PisDelivery
    @ManyToOne
    @JoinColumn(name="delivery_id")
    var pisDelivery:PisDelivery?=null ,
    
    // PisCake
    @ManyToOne
    @JoinColumn(name="cake_id")
    var pisCake:PisCake?=null ,
    
    // PisBakery
    @ManyToOne
    @JoinColumn(name="bakery_id")
    var pisBakery:PisBakery?=null 
): BaseEntity<Int>()
