/*
 * Java entity class for "PisDailyStock" 
 * Created on 2020/02/11 - Time 16:31:10 
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package bao.nguyen.PIS.entity;

import bao.nguyen.PIS.common.BaseEntity
import javax.persistence.*
import javax.validation.constraints.*;
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UpdateTimestamp



/**
 * Domain class for entity "PisDailyStock"
 *
 * @author Bao Nguyen
 *
 */
@Entity
@Table(name ="pis_daily_stock")
data class PisDailyStock (
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // 
     @NotNull
    var piece :Int  = 0,
    
    // PisBakery
    @ManyToOne
    @JoinColumn(name="bakery_id")
    var pisBakery:PisBakery?=null ,
    
    // PisCake
    @ManyToOne
    @JoinColumn(name="cake_id")
    var pisCake:PisCake?=null 
): BaseEntity<Int>()
