/*
 * Java entity class for "PisDailySale" 
 * Created on 2020/02/17 - Time 05:17:48 
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package bao.nguyen.PIS.entity;

import bao.nguyen.PIS.common.BaseEntity
import javax.persistence.*
import javax.validation.constraints.*;
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UpdateTimestamp



/**
 * Domain class for entity "PisDailySale"
 *
 * @author Rikai Technology
 *
 */
@Entity
@Table(name ="pis_daily_sale")
data class PisDailySale (
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // 
     @NotNull
    var piece :Int  = 0,
    
    // PisCake
    @ManyToOne
    @JoinColumn(name="cake_id")
    var pisCake:PisCake?=null ,
    
    // PisBakery
    @ManyToOne
    @JoinColumn(name="bakery_id")
    var pisBakery:PisBakery?=null 
): BaseEntity<Int>()
