/*
 * Java entity class for "PisSetting" 
 * Created on 2020/02/11 - Time 16:31:10 
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package bao.nguyen.PIS.entity;

import bao.nguyen.PIS.common.BaseEntity
import javax.persistence.*
import javax.validation.constraints.*;
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UpdateTimestamp



/**
 * Domain class for entity "PisSetting"
 *
 * @author Bao Nguyen
 *
 */
@Entity
@Table(name ="pis_setting")
data class PisSetting (
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // 
     var minStock :Int ? = null,

	// 
    var maxStock :Int ? = null,
    
    // PisCake
    @ManyToOne
    @JoinColumn(name="cake_id")
    var pisCake:PisCake?=null ,
    
    // PisBakery
    @ManyToOne
    @JoinColumn(name="bakery_id")
    var pisBakery:PisBakery?=null 
): BaseEntity<Int>()
