/*
 * Java entity class for "PisStore" 
 * Created on 2020/02/17 - Time 05:17:48 
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package bao.nguyen.PIS.entity;

import bao.nguyen.PIS.common.BaseEntity
import javax.persistence.*
import javax.validation.constraints.*;
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UpdateTimestamp

import java.util.Date;


/**
 * Domain class for entity "PisStore"
 *
 * @author Bao Nguyen
 *
 */
@Entity
@Table(name ="pis_store")
data class PisStore (
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // 
     @NotNull
    var piece :Int  = 0,

	// 
    var updateAt : Date? = null,

	// 
    var dailyUpdate : Date? = null,
    
    // PisBakery
    @ManyToOne
    @JoinColumn(name="bakery_id")
    var pisBakery:PisBakery?=null ,
    
    // PisCake
    @ManyToOne
    @JoinColumn(name="cake_id")
    var pisCake:PisCake?=null 
): BaseEntity<Int>()
