/*
 * Java entity class for "PisUser" 
 * Created on 2020/02/15 - Time 08:47:42
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package bao.nguyen.PIS.entity;

import bao.nguyen.PIS.common.BaseEntity
import javax.persistence.*
import javax.validation.constraints.*;
import org.hibernate.annotations.CreationTimestamp
import org.hibernate.annotations.UpdateTimestamp



/**
 * Domain class for entity "PisUser"
 *
 * @author Bao Nguyen
 *
 */
@Entity
@Table(name ="pis_user")
data class PisUser (
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    //
    @NotNull
    @Size( min = 1, max = 255 )
    var username : String = String(),

     @NotNull
    @Size( min = 1, max = 255 )
    var password : String = String(),

	// 
    @Size( max = 255 )
    var role : String? = null,
    
    // PisBakery
    @ManyToOne
    @JoinColumn(name="bakery_id")
    var pisBakery:PisBakery?=null 
): BaseEntity<Int>()
