/*
 * Created on 2020-02-17 ( Date ISO 2020-02-17 - Time 05:17:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package bao.nguyen.PIS.repository;

import bao.nguyen.PIS.entity.PisStore
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * Spring data Jpa repository for "PisStore" <br>
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
@Repository
interface PisStoreRepository : JpaRepository<PisStore, Int> {
}